[versions]
agp = "9.3.2"
ksp = "2.3.11"
kotlin = "2.4.20"
coreKtx = "1.19.0"
junit = "4.13.2"
junitVersion = "1.3.0"
appcompat = "1.8.0"
material = "1.14.0"
activity = "1.13.0"
constraintlayout = "2.2.2"
preference = "1.2.1"
recyclerview = "1.4.0"
lifecycleExt = "2.2.0"
lifecycleKtx = "2.11.0"
fragmentKtx = "1.9.0"
work = "2.11.2"
navigation = "2.10.1"
room = "2.8.5"
flexbox = "3.0.0"
coroutines = "1.11.0"
dagger = "2.60.1"
leakcanary = "2.14"
appUpdate = "2.1.0"
insets = "2.0.0"
datastore = "1.2.1"
exif = "1.4.2"
asyncInflater = "1.1.0"
ktor = "3.5.2"
glide = "5.0.9"
protobufx = "1.11.0"
protobuf-plugin = "0.10.0"
protobuf = "4.36.1"
jna = "5.19.1"
documentfile = "1.1.0"

[libraries]
kotlinx-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-core-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-protobuf = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-protobuf", version.ref = "protobufx" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-preference = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "lifecycleExt" }
androidx-lifecycle-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleKtx" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }
androidx-work = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
androidx-room = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-flexbox = { group = "com.google.android.flexbox", name = "flexbox", version.ref = "flexbox" }
androidx-datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
androidx-exif = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exif" }
androidx-async-inflater = { group = "androidx.asynclayoutinflater", name = "asynclayoutinflater", version.ref = "asyncInflater" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
dagger = { group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }
dagger-processor = { group = "com.google.dagger", name = "dagger-android-processor", version.ref = "dagger" }
leakcanary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakcanary" }
play-core = { group = "com.google.android.play", name = "app-update", version.ref = "appUpdate" }
play-core-ktx = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "appUpdate" }
insets = { group = "io.github.atomofiron", name = "extended-insets", version.ref = "insets" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-ksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
ktor-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protobuf" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }

android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
licenses = { id = "com.google.android.gms.oss-licenses-plugin", version = "0.13.0" }
